#!/usr/bin/env python3
"""Promote a passing full-profile UAT report to the blessed report set."""

from __future__ import annotations

import argparse
import json
import re
import shutil
from pathlib import Path


def main() -> int:
    parser = argparse.ArgumentParser(description="Copy a passing full UAT report into uat/reports/blessed.")
    parser.add_argument("--source", default="uat/reports/latest-uat-report.md", help="Markdown report generated by uat_suite.py")
    parser.add_argument("--out-dir", default="uat/reports/blessed", help="Directory for blessed report artifacts")
    args = parser.parse_args()

    source = Path(args.source)
    out_dir = Path(args.out_dir)
    if not source.exists():
        raise SystemExit(f"report does not exist: {source}")

    text = source.read_text(encoding="utf-8")
    decision = required_match(text, r"- \*\*Decision\*\*: ([^\n]+)", "decision")
    profile = required_match(text, r"- \*\*Profile\*\*: `([^`]+)`", "profile")
    summary = required_match(text, r"- \*\*Summary\*\*: ([^\n]+)", "summary")
    git_revision = required_match(text, r"- \*\*Git revision\*\*: `([^`]+)`", "git revision")

    if decision != "GO":
        raise SystemExit(f"refusing to bless non-GO report: {decision}")
    if profile != "full":
        raise SystemExit(f"refusing to bless non-full profile report: {profile}")

    passed, failed, blocked, total = parse_summary(summary)
    if failed or blocked or passed != total:
        raise SystemExit(f"refusing to bless failing report: {summary}")

    out_dir.mkdir(parents=True, exist_ok=True)
    latest = out_dir / "latest-uat-report.md"
    versioned = out_dir / f"bluedb-{git_revision[:7]}-full-uat-report.md"
    shutil.copyfile(source, latest)
    shutil.copyfile(source, versioned)

    badge = {
        "schemaVersion": 1,
        "label": "blessed UAT",
        "message": f"GO {passed}/{total}",
        "color": "brightgreen",
    }
    (out_dir / "uat-badge.json").write_text(json.dumps(badge, indent=2) + "\n", encoding="utf-8")
    print(f"Blessed {source} -> {latest}")
    print(f"Snapshot: {versioned}")
    return 0


def required_match(text: str, pattern: str, name: str) -> str:
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"could not find {name} in report")
    return match.group(1).strip()


def parse_summary(summary: str) -> tuple[int, int, int, int]:
    match = re.match(r"(\d+) passed, (\d+) failed, (\d+) blocked, (\d+) total", summary)
    if not match:
        raise SystemExit(f"could not parse summary: {summary}")
    return tuple(int(part) for part in match.groups())  # type: ignore[return-value]


if __name__ == "__main__":
    raise SystemExit(main())
